name: 'Setup ddev'
description: 'Set up your GitHub Actions workflow with ddev '
author: 'Jonas Eberle'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: cpu
  color: yellow
inputs:
  ddevDir:
    description: 'Directory where ddev is location if not in root directory'
    required: false
    default: '.'