on: [push, pull_request]
name: tests

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - uses: rfay/github-action-setup-ddev@20201204_remove_router_hack
